import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Hero, Features, Price, CTA } from '../components'
import { motion, useScroll } from 'framer-motion'


export default function Home() {
  const { scrollYProgress } = useScroll()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <Hero />
        <Features />
        <Price />
        <CTA />
      </main>
    </>
  )
}
